language: clojure
script: lein doo node "server-tests" once
before_install:
 - sudo add-apt-repository --yes ppa:ethereum/ethereum
 - sudo apt-get -qq update
before_script:
  - "echo 'Installing Solc'"
  - sudo apt-get --yes install solc
  - "echo 'Installing Ganache'"
  - npm install -g ganache-cli
  - "echo 'Running Ganache'"
  - ganache-cli -p 8549 &
  - "echo 'Compiling contracts'"
  - lein compile-solidity
